### ISSUE TITLE
QT program do not honour the desktop theme on Wayland after KDE Platform 5.13 update

### ISSUE THREAD

**Issue by ghost** [flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration#1] opened 2020-01-31 13:37 UTC
I use Telegram from the stable repository with the environmental flag override `--env=QT_QPA_PLATFORM=wayland`, and after the recent KDE Platform 5.13 update _(`56180094df53ad85ae2d3f51cc727337d294e1917e1fe741de494b089f38b950`)_ window decorations do not respect the host's theme, which is, in my case, Adwaita Dark, defaulting to the white Adwaita theme. 

Reverting to the commit `ff79e12498e077525c5658ad255468fb93d38943861ca9ec699f791070c86cd7` serves as a temporary workaround.

**Comment by grulja** [comment] 2020-01-31 13:45
That is weird, there was just update to newer KDE Frameworks which shouldn't have any effect on this. Do you have **org.kde.WaylandDecoration.QGnomePlatform-decoration** and **org.kde.PlatformTheme.QGnomePlatform** installed? 

What is the output when you run with `QT_DEBUG_PLUGINS=1 flatpak run --env=QT_QPA_PLATFORM=wayland org.telegram.desktop`?

**Comment by ghost** [comment] 2020-01-31 13:52
I do have them installed.

```
$ flatpak list
(...)
Adwaita dark GTK theme                  org.gtk.Gtk3theme.Adwaita-dark                                 3.22   flathub         system
Adwaita theme                           org.kde.KStyle.Adwaita                                         5.12   flathub         system
Adwaita theme                           org.kde.KStyle.Adwaita                                         5.13   flathub         system
KDE Application Platform                org.kde.Platform                                               5.12   flathub         system
KDE Application Platform                org.kde.Platform                                               5.13   flathub         system
QGnomePlatform                          org.kde.PlatformTheme.QGnomePlatform                           5.12   flathub         system
QGnomePlatform                          org.kde.PlatformTheme.QGnomePlatform                           5.13   flathub         system
QGnomePlatform-decoration               org.kde.WaylandDecoration.QGnomePlatform-decoration            5.12   flathub         system
QGnomePlatform-decoration               org.kde.WaylandDecoration.QGnomePlatform-decoration            5.13   flathub         system
Krita                                   org.kde.krita                                       4.2.8.0    stable flathub         system
Telegram Desktop                        org.telegram.desktop                                1.9.9      stable flathub         system
```


The output is as follows in the linked gist:
https://gist.github.com/Bryophyllum/aee97d7e54117969d13d8a14d31fc23c

**Comment by grulja** [comment] 2020-01-31 14:52
This seems to be caused by https://github.com/flatpak/flatpak/issues/3397.

**Comment by Erick555** [comment] 2020-02-01 13:23
@grulja the problem was that qt 5.14 was committed (56180094df53ad85ae2d3f51cc727337d294e1917e1fe741de494b089f38b950) to 5.13 branch which caused such issues for existing apps. It's no longer there though.

**Comment by ghost** [comment] 2020-02-01 13:42
I'm on `b1061ddc93f87193b8fa8005c8615f573477108f90331a7f6f1015f3d85617a8` right now, and I'm experiencing this issue again: https://github.com/flathub/org.telegram.desktop/issues/101#issuecomment-559998168.

Downgrading `org.kde.WaylandDecoration.QGnomePlatform-decoration` to `b7e335624f8a7aab1749e84b00b6a0a9489a4100f224e60e39661a296375a33a` reverts the state of things back to the one from the description of this issue _(the white Adwaita theme window decorations)_

Attaching logs:
![Screenshot from 2020-02-01 14-03-48](https://user-images.githubusercontent.com/27376783/73593201-94aef800-4501-11ea-88e8-811ae04a3e63.png)
https://gist.github.com/Bryophyllum/d172d0c92cbcbe4061eaeaf6a32164e1 when `org.kde.WaylandDecoration.QGnomePlatform-decoration//5.13` is at the commit **`b7e335624f8a7aab1749e84b00b6a0a9489a4100f224e60e39661a296375a33a`**, and `org.kde.Platform//5.13` is at the commit **`b1061ddc93f87193b8fa8005c8615f573477108f90331a7f6f1015f3d85617a8`**.
___

![Screenshot from 2020-02-01 14-02-22](https://user-images.githubusercontent.com/27376783/73593211-ccb63b00-4501-11ea-9171-54cee0160266.png)
https://gist.github.com/Bryophyllum/d8411e787722f5ae6274d4b96930aaa7 when `org.kde.WaylandDecoration.QGnomePlatform-decoration//5.13` is at the commit **`461955b0c8fa48700c3b5441a65beaeaa0692414469f41f94e453652e89287b5`**, and `org.kde.Platform//5.13` is at the commit **`b1061ddc93f87193b8fa8005c8615f573477108f90331a7f6f1015f3d85617a8`**.

**EDIT:**
___

![Screenshot from 2020-02-01 14-51-15](https://user-images.githubusercontent.com/27376783/73593257-56fe9f00-4502-11ea-9f94-f199ba71d533.png)
https://gist.github.com/Bryophyllum/a788afd444eeaa35b9e951458923263a when `org.kde.WaylandDecoration.QGnomePlatform-decoration//5.13` is at the commit **`b7e335624f8a7aab1749e84b00b6a0a9489a4100f224e60e39661a296375a33a`**, and `org.kde.Platform//5.13` is at the commit **`ff79e12498e077525c5658ad255468fb93d38943861ca9ec699f791070c86cd7`**.

**Comment by grulja** [comment] 2020-02-01 14:54
This will be fixed with the next update of the KDE runtime and both QGnomePlatform and QGnomePlatform-decoration. There was a Qt version mismatch and when I did rebuild for Qt 5.13, it actually did rebuild against Qt 5.14.

**Closed as completed by grulja** 2020-02-01 14:54 UTC
