### ISSUE TITLE
Rebuild org.kde.WaylandDecoration.QGnomePlatform-decoration when org.kde.Platform upgrades

### ISSUE THREAD

**Issue by taoky** [flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration#5] opened 2022-10-12 05:54 UTC
After upgrading `org.kde.Platform:5.15-21.08` to latest version, I find that `org.sqlitebrowser.sqlitebrowser` crashes when I move mouse cursor to the maximum/minimum/close button in decoration in GNOME Wayland session, and its decoration is provided by `org.kde.WaylandDecoration.QGnomePlatform-decoration:5.15-21.08`.

As far as I know, QGnomePlatform uses private Qt headers and requires rebuilding every time Qt upgrades. Here are two related bug reports about this bug in Arch packages:

- https://bugs.archlinux.org/task/76053
- https://bugs.archlinux.org/task/76109

I'm not sure how to debug coredump produced by flatpak apps (GDB cannot find corresponding library files), but I believe that this bug is identical with these above and rebuilding workarounds this bug.

**Comment by travier** [comment] 2022-10-12 08:58
Thanks for letting us know. I've triggered a build. Hopefully that helps.

We should start documenting those steps that we need to do for each Platform update.

**Comment by travier** [comment] 2022-10-12 09:17
OK, now we need to fix the build:

```
flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions org.kde.WaylandDecoration.QGnomePlatform-decoration.json
 in dir /srv/buildbot/worker/build-x86_64-1/build (timeout 1200 secs)
 watching logfiles {}
 argv: b'flatpak run --command=flatpak-builder-lint org.flatpak.Builder --exceptions org.kde.WaylandDecoration.QGnomePlatform-decoration.json'
 using PTY: False
{
    "errors": [
        "module-qgnomeplatform-decoration-source-git-branch",
        "module-Adwaita-qt-source-git-no-commit-or-tag",
        "module-qgnomeplatform-decoration-source-git-no-commit-or-tag",
        "module-Adwaita-qt-source-git-branch"
    ],
    "warnings": [
        "module-Adwaita-qt-cmake-redundant-prefix",
        "module-qgnomeplatform-decoration-cmake-redundant-prefix"
    ]
}
If you think problems listed above are a false positive, please report it here:
  https://github.com/flathub/flatpak-builder-lint
program finished with exit code 1
```

**Comment by q234rty** [comment] 2022-10-14 18:46
I assume the build failure is caused by the modules being on a branch and not a specific commit?

**Comment by DominiqueSite** [comment] 2022-10-17 06:51
I have the same problem with KeePassXC, QOwnNotes and Nextcloud Desktop, please fix this as soon as possible!

**Comment by travier** [comment] 2022-10-17 11:06
Note that those are linter failures https://github.com/flathub/flatpak-builder-lint and have nothing to do with this repo. Please file issues there.

**Comment by travier** [comment] 2022-10-17 11:07
For KeePassXC, etc.

**Comment by q234rty** [comment] 2022-10-17 11:38
@travier Did you actually push the rebuilt org.kde.WaylandDecoration.QGnomePlatform-decoration? Flatpak info still says the last build is from september 20th and all qt apps still crash when hovering the close button. This is resolved by simply manually rebuilding org.kde.WaylandDecoration.QGnomePlatform-decoration using flatpak-builder.

**Comment by q234rty** [comment] 2022-10-17 11:41
And no, this is a runtime extension issue, not an issue for those apps, as those apps run fine without this runtime extension.

**Comment by grulja** [comment] 2022-10-17 12:02
I'm building it now.

**Comment by grulja** [comment] 2022-10-17 12:06
> I'm building it now.

Hmm, fails with the same reason as mentioned above. I'll check.

**Comment by travier** [comment] 2022-10-17 12:41
OK, sorry, I misunderstood your comment then. I triggered a rebuild in https://buildbot.flathub.org/#/apps/org.kde.WaylandDecoration.QGnomePlatform-decoration which resulted in the error mentioned in https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration/issues/5#issuecomment-1275851518.

~~We'll have to file an exception in https://github.com/flathub/flatpak-builder-lint for that repo.~~

**Comment by q234rty** [comment] 2022-10-17 12:43
> We'll have to file an exception in https://github.com/flathub/flatpak-builder-lint for that repo.

Why don't just use a commit instead of a branch?

**Comment by travier** [comment] 2022-10-17 12:43
https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration/pull/6

**Comment by grulja** [comment] 2022-10-17 13:04
I think this can be closed now.

**Closed as completed by grulja** 2022-10-17 13:04 UTC
